Create config
dmahfouda/tin-can-phone pull request #4
Opened 2020-03-22 19:57 UTC by dmahfouda

Hi Mikey, I pulled out the environment variables! Take a look!

2020-03-23 04:10 UTC, mgoldenberg requested changes
This looks good! I think just a few small changes and we're ready to merge, see the comments in the files.

2020-03-23 04:10 UTC, mgoldenberg commented on tin-can-phone.ino
> +    can.openWebSocket(TIN_CAN_SWITCH, 3000);
Hm, I forgot about the port. Let's add another configuration constant for that and change the name of `TIN_CAN_SWITCH` to represent the host (i.e. server name or ip). In other words, we'd have:

- `TIN_CAN_SWITCH_HOST`
- `TIN_CAN_SWITCH_PORT`

2020-03-23 04:10 UTC, mgoldenberg commented on tin-can-phone.ino
On line 269, below here, you should build the URL with the constants defined in the configuration file.

2020-03-23 04:12 UTC, mgoldenberg commented on tin-can-phone.ino
(You can't see the line I'm referring to in this snippet, by the way. For some reason I couldn't comment on a part of the code that hasn't changed.)

2020-03-24 00:58 UTC, dmahfouda commented
Hi @mgoldenberg take another look. I'm not able to see the websocket with this version, but all of the config variables are now compiling. This should resolves #3

2020-03-24 04:41 UTC, mgoldenberg commented
Looks great!

2020-03-24 04:41 UTC, mgoldenberg approved these changes

2020-03-24 04:41 UTC, merged